### PR TITLE
Spacing fix benchmark 1 to fix the spacing on Xmx and reupdated the a…

### PR DESCRIPTION
**Pull request by ea89**
…nalysis section

### CODE REVIEW

**Comment by 1heart** [comment]
Mind resolving the conflicts or rebasing with master?

**Comment by ea89** [comment]
I ll resolve it now

On Oct 9, 2015, at 1:54 AM, Yixin Lin <notifications@github.com<mailto:notifications@github.com>> wrote:

Mind resolving the conflicts or rebasing with master?

**Comment by ea89** [comment]
Do you want me to merge with the master?

On Oct 9, 2015, at 1:54 AM, Yixin Lin <notifications@github.com<mailto:notifications@github.com>> wrote:

Mind resolving the conflicts or rebasing with master?

**Comment by ea89** [comment]
I rebased with the master but didn't want to merge it in before prof Forbes or Azhar approved it.

On Oct 9, 2015, at 1:54 AM, Yixin Lin <notifications@github.com<mailto:notifications@github.com>> wrote:

Mind resolving the conflicts or rebasing with master?

**Comment by 1heart** [comment]
Redundant pull request (see #24)

**Pull request closed without merging**
